### PR TITLE
modernize code to build with maven again

### PR DESCRIPTION
**Pull request by cdietrich**
modernize code to build with maven again
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@kbirken would be nice if you could give it a try

**Comment by cdietrich** [comment]
any feedback here?

**Comment by kbirken** [comment]
No time yet, but still on my list.

**Comment by kbirken** [comment]
Meanwhile, I could build it locally without any problems. I am about to use it for an update of https://github.com/franca/franca, but this isn't finished yet.

**Pull request merged**
